### ISSUE TITLE
Mentor div bottom line are not at the same level

### ISSUE THREAD

**Issue by WebShivam** [praveenscience/LGMSoC-Public-Data#20]
![Screenshot_32](https://user-images.githubusercontent.com/64413107/122237353-e4b31280-cedc-11eb-8bb8-02a801df082a.jpg)

Here is the preview for better clarification 👆

**Comment by praveenscience** [comment]
Yes, it is intended too. Coz we have different sizes of content. Also, will see if I can make everything same size, but it might not look good. What say?

**Comment by praveenscience** [comment]
No comments after that so closing this.
