### ISSUE TITLE
Linking discord channel to website. 

### ISSUE THREAD

**Issue by ritik-vashist** [praveenscience/LGMSoC-Public-Data#22]
@praveenscience I would like to work on it can you please assign this task to me?

**Comment by NancyNegi23** [comment]
@praveenscience Sir I would like work on this issue..Please assign me this?

**Comment by ritik-vashist** [comment]
@NancyNegi23  I asked praveen sir to assign this task to me. But I think this has been done already. 
You may ask for another issue.

**Comment by praveenscience** [comment]
I don't understand how you both are going to do with nothing? 🤔  You don't have the code, definitely the password is not gonna be given to you, as it's production server! 😅

**Comment by praveenscience** [comment]
Anyway, this is done. Thanks for reporting. 👍
