### ISSUE TITLE
Irresponsive Reaction Buttons on Website

### ISSUE THREAD

**Issue by nishant-giri** [praveenscience/LGMSoC-Public-Data#26]
Registration button labelled as 'REGISTER AS PROJECT ADMIN' is not redirecting to a new webpage like the other registration buttons.

Buttons labelled as 'PROJECTS' and 'REGISTER' are not responsive. 

Social Media buttons on the Homepage Banner are not responsive.

**Comment by praveenscience** [comment]
These have been fixed. Can you please confirm this once for me?

**Comment by nishant-giri** [comment]
Yeah, the buttons are responsive. All the issues have been fixed.

**Comment by praveenscience** [comment]
Thanks for confirming @nishant-giri
