### ISSUE TITLE
Reordering navbar elements

### ISSUE THREAD

**Issue by namanmathur007** [praveenscience/LGMSoC-Public-Data#33]
"About us" before our "programme" in navbar looks a bit weird

**Comment by NancyNegi23** [comment]
@praveenscience  sir can I work on this??....Assign me this issue.

**Comment by praveenscience** [comment]
@NancyNegi23 How are you gonna work when the source code is not available to you. 🤔

**Comment by NancyNegi23** [comment]
Sir I thought you made the source code public...My bad!
